# Immich Go Backend Configuration
server:
  address: "0.0.0.0:3001"
  grpc_address: "0.0.0.0:3002"
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s

database:
  url: "postgres://immich:immich@localhost:5432/immich?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 10
  max_conn_lifetime: 1h
  connect_timeout: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"

auth:
  jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
  jwt_expiry: "24h"
  jwt_refresh_expiry: "168h"
  jwt_issuer: "immich-go-backend"
  registration_enabled: true

storage:
  upload_location: "./uploads"
  library_location: "./library"
  thumbs_location: "./thumbs"
  profile_location: "./profile"
  video_location: "./encoded-video"

features:
  oauth_enabled: false
  facial_recognition: true
  smart_search: true
  trash: true
  sidecar: true
  map: true
  duplicate_detection: true

mail:
  enabled: false
  smtp:
    host: ""
    port: 587
    username: ""
    password: ""
    from: "noreply@immich.app"

external:
  domain: ""
  login_page_message: ""

jobs:
  enabled: true
  redis_url: "redis://localhost:6379/0"
  workers: 4
  concurrency: 10
  queue_name: "immich"
  
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  
machine_learning:
  enabled: true
  url: "http://localhost:3003"
  clip:
    enabled: true
    model_name: "ViT-B-32__openai"
  facial_recognition:
    enabled: true
    model_name: "buffalo_l"
    min_score: 0.7
