// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlbum = `-- name: GetAlbum :one
SELECT id, "ownerId", "albumName", "createdAt", "albumThumbnailAssetId", "updatedAt", description, "deletedAt", "isActivityEnabled", "order", "updateId" FROM albums
WHERE id = $1
`

func (q *Queries) GetAlbum(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.OwnerId,
		&i.AlbumName,
		&i.CreatedAt,
		&i.AlbumThumbnailAssetId,
		&i.UpdatedAt,
		&i.Description,
		&i.DeletedAt,
		&i.IsActivityEnabled,
		&i.Order,
		&i.UpdateId,
	)
	return i, err
}
