{{- if eq (include "immich-go-backend.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich-go-backend.fullname" . }}
  labels:
    {{- include "immich-go-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.url }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if .Values.auth.jwtSecret }}
  AUTH_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.redis.url }}
  JOBS_REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
  {{- if and .Values.storage.s3.enabled (eq .Values.storage.backend "s3") }}
  {{- if .Values.storage.s3.accessKeyId }}
  S3_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.storage.s3.secretAccessKey }}
  S3_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretAccessKey | quote }}
  {{- end }}
  {{- end }}
{{- end }}
