apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich-go-backend.fullname" . }}
  labels:
    {{- include "immich-go-backend.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.http.nodePort }}
      nodePort: {{ .Values.service.http.nodePort }}
      {{- end }}
    {{- if .Values.service.grpcEnabled }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      appProtocol: kubernetes
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.grpc.nodePort }}
      nodePort: {{ .Values.service.grpc.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "immich-go-backend.selectorLabels" . | nindent 4 }}
